// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlitedb

type Player struct {
	ID        string
	Username  string
	CreatedOn string
}

type PlayerSkill struct {
	PlayerID   string
	Name       string
	Day        string
	Level      int64
	Experience float64
}
